spring:
  application:
    name: security-service
  kafka:
    queues:
      student: student-saving-queue
      email: email-sending-greeting-queue
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: http://localhost:9092
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/auth-service
    password: qaisar
    username: qaisar
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.xml
  main:
    banner-mode: off
  jpa:
    hibernate:
#      ddl-auto: create
keycloak:
  issuer-uri: http://localhost:10190/auth/realms/university-portal-realm
  keys: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6WUeKb2QCMa9DGrvW9GUQLqLAgXy9W5N80nXm4bz8bXcplZy70/4IvC6D1PyBVmfrbAda4mFN7ZwC0qf4afN5GFKqJtN8R6qOg4J1CvUNDThqcJegbjXHzh1pWkAPDyxIgH0sytOA2VFd8Ywmq+xkq8MUGs4+NZiyEOwQQ+yOdJMUk8eMMxm5perFVOZMuflx26g14UZuPHf3Qtiy33wLP6rtT0hCTyDT6nz+lAjKFwAs8DdnjHkRKwt2MXJYMqrt5n3d2saS5+V89Yu9EGZjUjSF5HVUs2FSs6MCaKqFW+Dmuaab2SxMsz8mfH3Zbbras2a7ud5yOwShIM+pgqxmwIDAQAB
server:
  port: 8091