version: '3'
services:
  postgres-student:
    container_name: student-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: student-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/student:/data/postgres
  postgres-identity:
    container_name: identity-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: identity-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/identity:/data/postgres
  postgres-grading:
    container_name: grading-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: grading-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/grading:/data/postgres
  mysql-subject:
    container_name: subject-service-db
    image: mysql:8.3.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subject-service
      MYSQL_USER: qaisar
      MYSQL_PASSWORD: qaisar
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/subject:/var/lib/mysql
  postgres-scheduling:
    container_name: scheduling-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: scheduling-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5435:5432"
    volumes:
      - ./volumes/scheduling:/data/postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - university-portal
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - university-portal
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis
    ports:
      - "6379:6379"
networks:
  university-portal:
    driver: bridge