version: '3'
services:
#  keycloak-database:
#    container_name: keycloak-database
#    image: postgres:14
#    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: keycloak_db
#    ports:
#      - "5432:5432"
  postgres-student:
    container_name: student-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: student-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/student:/data/postgres
  postgres-grading:
    container_name: grading-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: grading-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5434:5432"
    volumes:
      - ./volumes/grading:/data/postgres
  postgres-scheduling:
    container_name: scheduling-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: scheduling-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5435:5432"
    volumes:
      - ./volumes/scheduling:/data/postgres
  postgres-faculty:
    container_name: faculty-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: faculty-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5436:5432"
    volumes:
      - ./volumes/faculty:/data/postgres
  postgres-auth:
    container_name: auth-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5437:5432"
    volumes:
      - ./volumes/auth:/data/postgres
  mysql-subject:
    container_name: subject-service-db
    image: mysql:8.3.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subject-service
      MYSQL_USER: qaisar
      MYSQL_PASSWORD: qaisar
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/subject:/var/lib/mysql
  mysql-storage:
    container_name: storage-service-db
    image: mysql:8.3.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storage-service
      MYSQL_USER: qaisar
      MYSQL_PASSWORD: qaisar
    ports:
      - "3308:3306"
    volumes:
      - ./volumes/storage:/var/lib/mysql
  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: '1000'
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - ./config/victoria-metrics/promscrape.yaml:/promscrape.yaml
    ports:
      - '8428:8428'
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - "8082:8080"
    command: start-dev --import-realm
#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:legacy
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: keycloak-database
#      DB_DATABASE: keycloak_db
#      DB_USER: admin
#      DB_SCHEMA: public
#      DB_PASSWORD: admin
#      KEYCLOAK_HOST_NAME: backend-keycloak-auth
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#    ports:
#      - "10190:8080"
#    depends_on:
#      - keycloak-database
#    command: [ "-b", "0.0.0.0", "--server-config", "standalone-ha.xml", "-Dkeycloak.import=/opt/keycloak/data/import/realm-settings.json" ]
#    volumes:
#      - ./config/keycloak/:/opt/keycloak/data/import/
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - university-portal
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - university-portal
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis
    ports:
      - "6379:6379"
networks:
  university-portal:
    driver: bridge