version: '3'
services:
  postgres-student:
    container_name: student-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: student-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
        - "5432:5432"
    volumes:
      - ./volumes/student:/data/postgres
  postgres-identity:
    container_name: identity-service-db
    image: postgres:14
    environment:
      POSTGRES_DB: identity-service
      POSTGRES_USER: qaisar
      POSTGRES_PASSWORD: qaisar
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/identity:/data/postgres