spring:
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5438/news-service
    username: qaisar
    password: qaisar
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - develop
  main:
    banner-mode: off
aws:
  s3:
    bucket:
      content-bucket: NEWS_CONTENT
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - prometheus
# Actuator Configuration
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
      circuitbreakers:
        enabled: true
    shutdown:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
server:
  port: 8780