spring:
  application:
    name: news-service
  datasource:
    url: jdbc:postgresql://localhost:5438/news-service
    username: qaisar
    password: qaisar
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
aws:
  s3:
    bucket:
      content-bucket: NEWS_CONTENT
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html