#spring:
#  config:
#    import: optional:configserver:http://localhost:1991
#  cloud:
#    config:
#      name: api-gateway

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}
      client:
        provider:
          keycloak:
#            authorization-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}/protocol/openid-connect/auth
#            token-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}/protocol/openid-connect/token
#            user-info-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
#            jwk-set-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            issuer-uri: ${keycloak-client.server-url}/auth/realms/${keycloak-client.realm}
#            user-name-attribute: qaisar04
#            user-info-authentication-method: header
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: PADebL0ChjTOhPPZLQs1Ecz8T3rREh8j
            authorization-grant-type: client_credentials
#            client-authentication-method: client_secret_basic
            scope: discovery
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        student-server-url: lb://student-service
        grading-server-url: lb://grading-service
        discovery-server-url: http://localhost:8761
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
    org.springframework.security: DEBUG
server:
  port: 8080
  forward-headers-strategy: framework
cors:
  allowCredentials: false
  allowedOrigins: http://localhost:4200,http://127.0.0.1:5500
  allowedMethods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowedHeaders: origin,content-type,accept,authorization,cookie