spring:
  application:
    name: api-gateway
  main:
      web-application-type: reactive
  output:
      ansi:
        enabled: always
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace
server:
  port: 8080
