spring:
  application:
    name: faculty-department-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/faculty-service
    password: qaisar
    username: qaisar
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.xml
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 57505
