spring:
  application:
    name: faculty-department-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/faculty-service
    password: qaisar
    username: qaisar
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
    liquibase-schema: migration
  main:
    banner-mode: off
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: prometheus
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 57505