global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'news-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['news-service:8780']
        labels:
          application: 'News Service Application'