scrape_configs:
  - job_name: 'news-servce'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ "127.0.0.1:8780" ]
        labels:
          application: 'news-servce'