qr:
  width: 600
  height: 600
  charset: UTF-8
server:
  port: 8070
spring:
  main:
    banner-mode: off
  application:
    name: qr-service
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework:
      web: debug
      security: debug