spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://postgres:5432/student-service
    driver-class-name: org.postgresql.Driver
    username: qaisar
    password: qaisar
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
server:
  port: 8081
