eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # не регистрировать этот клиент в Eureka
    fetch-registry: false # не получать информацию о других службах из Eureka
server:
  port: 8761
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0