spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:10190/auth/realms/university-portal-realm
          jwk-set-uri: http://localhost:10190/auth/realms/university-portal-realm/protocol/openid-connect/certs
  application:
    name: grading-service
  datasource:
    url: jdbc:postgresql://localhost:5434/grading-service
    username: qaisar
    password: qaisar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 8087