spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: invitation-code-service
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 1465