#spring:
#  config:
#    import: optional:configserver:http://localhost:1991
#  cloud:
#    config:
#      name: student-service

spring:
  #  security:
  #    oauth2:
  #     resourceserver:
  #       jwt:
  #         issuer-uri: http://localhost:8082/realms/university-portal-realm
  kafka:
    queues:
      student: student-saving-queue
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
        json:
          trusted:
          packages: "*"
      bootstrap-servers: http://localhost:9092
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5433/student-service
    driver-class-name: org.postgresql.Driver
    username: qaisar
    password: qaisar
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: prometheus
aws:
  s3:
    default:
      avatar: https://placeholder-images-uni-portal-v1.s3.ap-south-1.amazonaws.com/d2244ea084c84df19a022eb43e58351e
    bucket:
      profile-bucket: USER_PROFILE_IMAGE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html
server:
  port: 8081