spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:10190/auth/realms/university-portal-realm
          jwk-set-uri: http://localhost:10190/auth/realms/university-portal-realm/protocol/openid-connect/certs
  application:
    name: subject-service
  datasource:
    url: jdbc:mysql://localhost:3306/subject-service
    password: qaisar
    username: qaisar
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 8308