spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/qaisar04/university-portal-configuration
#          clone-on-start: true
#          default-label: main
        native:
          search-locations: classpath:/configurations
  main:
    banner-mode: off
server:
  port: 1991
