name: CI/CD Student Service

on:
  push:
    branches:
      - main
    paths:
      - 'student-service/**'
jobs:
  student-service:
    name: Student Service
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: unit tests
        run: mvn -B test --file student-service/pom.xml

      - name: build the application
        run: |
          mvn clean
          mvn -B package --file student-service/pom.xml

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./student-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/student-service:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./student-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/student-service:latest