name: CI/CD Subject Service

on:
  push:
    branches:
      - main
    paths:
      - 'subject-service/**'
jobs:
  api-gateway:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository subject service
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: build and push docker image
        run: |
          cd subject-service
          mvn compile jib:build  -DskipTests\
            -Djib.to.auth.username=$DOCKER_USERNAME\
            -Djib.to.auth.password=$DOCKER_PASSWORD